In [1]:
import numpy as np
import pandas as pd
from math import pow

In [ ]:
df = pd.read_csv('data/athlete_events.csv', sep=',')

In [54]:
df[:20]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
16,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
17,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
18,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
19,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN

In [56]:
# PARTICIPANTS TABLE PREPARE
participants = df.loc[:, 'Name':'Team'] # взять часть столбцов из таблицы (срез по столбцам)
participants[:20]

                        Name Sex   Age  Height  Weight            Team
0                  A Dijiang   M  24.0   180.0    80.0           China
1                   A Lamusi   M  23.0   170.0    60.0           China
2        Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark
3       Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden
4   Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands
5   Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands
6   Christine Jacoba Aaftink   F  25.0   185.0    82.0     Netherlands
7   Christine Jacoba Aaftink   F  25.0   185.0    82.0     Netherlands
8   Christine Jacoba Aaftink   F  27.0   185.0    82.0     Netherlands
9   Christine Jacoba Aaftink   F  27.0   185.0    82.0     Netherlands
10           Per Knut Aaland   M  31.0   188.0    75.0   United States
11           Per Knut Aaland   M  31.0   188.0    75.0   United States
12           Per Knut Aaland   M  31.0   188.0    75.0   United States
13           Per Knut Aaland   M  31.0   188.0    75.0   United States
14           Per Knut Aaland   M  33.0   188.0    75.0   United States
15           Per Knut Aaland   M  33.0   188.0    75.0   United States
16           Per Knut Aaland   M  33.0   188.0    75.0   United States
17           Per Knut Aaland   M  33.0   188.0    75.0   United States
18              John Aalberg   M  31.0   183.0    72.0   United States
19              John Aalberg   M  31.0   183.0    72.0   United States

In [48]:
res = participants.drop_duplicates(subset='Name', keep='last') # удалить дубликаты по столбцу 
res

,Name,Sex,Age,Height,Weight,Team
0,A Dijiang,M,24.0,180.0,80.0,China
1,A Lamusi,M,23.0,170.0,60.0,China
2,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark
3,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden
9,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands
17,Per Knut Aaland,M,33.0,188.0,75.0,United States
25,John Aalberg,M,33.0,183.0,72.0,United States
27,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands
28,Antti Sami Aalto,M,26.0,186.0,96.0,Finland
29,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland
30,Jorma Ilmari Aalto,M,22.0,182.0,76.5,Finland
31,Jyri Tapani Aalto,M,31.0,172.0,70.0,Finland
33,Minna Maarit Aalto,F,34.0,159.0,55.5,Finland
34,Pirjo Hannele Aalto (Mattila-),F,32.0,171.0,65.0,Finland
39,Arvo Ossian Aaltonen,M,34.0,NaN,NaN,Finland
40,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland
56,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland
57,Timo Antero Aaltonen,M,31.0,189.0,130.0,Finland
58,Win Valdemar Aaltonen,M,54.0,NaN,NaN,Finland
78,Kjetil Andr Aamodt,M,34.0,176.0,85.0,Norway
79,Ragnhild Margrethe Aamodt,F,27.0,163.0,NaN,Norway
80,Andreea Aanei,F,22.0,170.0,125.0,Romania
82,Fritz Aanes,M,26.0,187.0,89.0,Norway
85,Nils Egil Aaness,M,27.0,NaN,NaN,Norway
86,Alf Lied Aanning,M,24.0,NaN,NaN,Norway
87,Agnes Erika Aanonsen (-Eyde),F,17.0,169.0,65.0,Norway
88,Johan Aantjes,M,26.0,NaN,NaN,Netherlands
90,Jan-Erik Aarberg,M,47.0,170.0,77.0,Norway
91,Willemien Aardenburg,F,22.0,NaN,NaN,Netherlands
93,Pepijn Aardewijn,M,30.0,189.0,72.0,Netherlands
...,...,...,...,...,...,...
271043,Werner Zwingli,M,29.0,NaN,NaN,Switzerland
271044,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States
271046,Krzysztof Zwoliski,M,21.0,175.0,70.0,Poland
271049,Henk Jan Zwolle,M,31.0,197.0,93.0,Netherlands
271051,Sandra Kornelia Zwolle,F,26.0,174.0,65.0,Netherlands
271055,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan
271056,Yury Ivanovich Zyabrev,M,25.0,174.0,62.0,Soviet Union
271061,Nataliya Vasilyevna Zyatikova,F,27.0,162.0,53.0,Belarus
271065,Vera Vasilyevna Zyatikova,F,27.0,161.0,53.0,Belarus
271074,Vladislavas Zybaila,M,27.0,178.0,75.0,Lithuania
271075,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland
271080,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union
271085,Bogusaw Zych,M,36.0,182.0,82.0,Poland
271086,Micha Zych,M,23.0,177.0,68.0,Poland
271088,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland
271090,Dominik ycki,M,38.0,192.0,95.0,Poland
271091,ukasz Tomasz ygado,M,32.0,200.0,89.0,Poland
271098,Pawe Jan Zygmunt,M,33.0,182.0,79.0,Poland
271099,Stavroula Zygouri,F,36.0,171.0,63.0,Greece
271100,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia
271101,Milan Zyka,M,24.0,173.0,68.0,Czechoslovakia
271103,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia
271104,Yevgeny Aleksandrovich Zykov,M,22.0,172.0,65.0,Russia-1
271106,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina
271107,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States
271109,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia
271110,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus
271111,Andrzej ya,M,29.0,179.0,89.0,Poland-1
271113,Piotr ya,M,27.0,176.0,59.0,Poland
271115,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland

In [49]:
# GAMES TABLE PREPARE
games = df.loc[:, 'Year':'City']
res_games = games.drop_duplicates()
res_games

      Year  Season                    City
0     1992  Summer               Barcelona
1     2012  Summer                  London
2     1920  Summer               Antwerpen
3     1900  Summer                   Paris
4     1988  Winter                 Calgary
6     1992  Winter             Albertville
8     1994  Winter             Lillehammer
26    1932  Summer             Los Angeles
28    2002  Winter          Salt Lake City
29    1952  Summer                Helsinki
30    1980  Winter             Lake Placid
31    2000  Summer                  Sydney
32    1996  Summer                 Atlanta
35    1912  Summer               Stockholm
39    1924  Summer                   Paris
40    2014  Winter                   Sochi
41    1948  Summer                  London
68    1998  Winter                  Nagano
77    2006  Winter                  Torino
79    2008  Summer                 Beijing
80    2016  Summer          Rio de Janeiro
82    2004  Summer                  Athina
83    1960  Winter            Squaw Valley
85    1964  Winter               Innsbruck
87    1984  Winter                Sarajevo
88    1984  Summer             Los Angeles
89    1968  Summer             Mexico City
90    1972  Summer                  Munich
91    1988  Summer                   Seoul
94    1936  Summer                  Berlin
110   1952  Winter                    Oslo
111   1956  Winter       Cortina d'Ampezzo
128   1956  Summer               Melbourne
129   1960  Summer                    Roma
133   1928  Summer               Amsterdam
145   1976  Summer                Montreal
188   1980  Summer                  Moskva
192   1964  Summer                   Tokyo
245   2010  Winter               Vancouver
266   1968  Winter                Grenoble
268   1906  Summer                  Athina
626   1972  Winter                 Sapporo
628   1976  Winter               Innsbruck
672   1924  Winter                Chamonix
711   1904  Summer               St. Louis
935   1928  Winter            Sankt Moritz
1149  1908  Summer                  London
1187  1948  Winter            Sankt Moritz
1326  1932  Winter             Lake Placid
1327  1936  Winter  Garmisch-Partenkirchen
3079  1896  Summer                  Athina
6194  1956  Summer               Stockholm

In [50]:
# EVENTS TABLE PREPARE
events = df.loc[:, 'Sport':'Event']
events = events.drop_duplicates(subset='Event', keep='last')
events

,Sport,Event
109352,Croquet,Croquet Mixed Doubles
117809,Athletics,Athletics Men's All-Around Championship
123223,Figure Skating,Figure Skating Men's Special Figures
147806,Swimming,Swimming Men's 100 metres Freestyle For Sailors
157315,Gymnastics,"Gymnastics Men's Individual All-Around, 4 Events"
177943,Shooting,"Shooting Men's Muzzle-Loading Pistol, 25 metres"
180286,Shooting,"Shooting Men's Free Pistol, 30 metres"
185107,Racquets,Racquets Men's Singles
185108,Racquets,Racquets Men's Doubles
185185,Swimming,Swimming Men's 500 metres Freestyle
186006,Sailing,Sailing Mixed 10-20 Ton
197536,Swimming,Swimming Men's 220 yard Freestyle
200079,Sailing,Sailing Mixed 18 foot
202021,Athletics,"Athletics Men's 4,000 metres Steeplechase"
209259,Swimming,Swimming Men's Plunge For Distance
212985,Cycling,Cycling Men's 1/3 mile
212988,Cycling,Cycling Men's 2 mile
213103,Cycling,"Cycling Men's 10,000 metres"
214105,Aeronautics,Aeronautics Mixed Aeronautics
215492,Fencing,"Fencing Men's epee, Masters and Amateurs, Indi..."
216862,Archery,Archery Men's Sur La Perche a La Herse
216863,Archery,Archery Men's Sur La Perche a La Pyramide
216980,Tennis,"Tennis Mixed Doubles, Covered Courts"
222402,Shooting,"Shooting Men's Running Target, Single And Doub..."
225266,Athletics,"Athletics Men's Javelin Throw, Both Hands"
228387,Athletics,Athletics Men's Standing Triple Jump
228388,Sailing,Sailing Mixed 30 metres
230588,Roque,Roque Men's Singles
232614,Sailing,Sailing Mixed 2-3 Ton
233168,Athletics,Athletics Men's 56-pound Weight Throw
...,...,...
271070,Cross Country Skiing,Cross Country Skiing Men's Sprint
271071,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres
271072,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres
271073,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres
271074,Cross Country Skiing,Cross Country Skiing Men's 10/10 kilometres Pu...
271077,Athletics,Athletics Women's Javelin Throw
271080,Athletics,Athletics Women's Shot Put
271083,Fencing,"Fencing Men's Foil, Individual"
271084,Fencing,"Fencing Men's Foil, Team"
271085,Fencing,"Fencing Men's epee, Team"
271086,Figure Skating,Figure Skating Mixed Ice Dancing
271087,Swimming,Swimming Men's 100 metres Butterfly
271088,Swimming,Swimming Men's 200 metres Butterfly
271090,Sailing,Sailing Men's Two Person Keelboat
271091,Volleyball,Volleyball Men's Volleyball
271094,Speed Skating,"Speed Skating Men's 1,500 metres"
271097,Speed Skating,"Speed Skating Men's 10,000 metres"
271098,Speed Skating,"Speed Skating Men's 5,000 metres"
271099,Wrestling,"Wrestling Women's Middleweight, Freestyle"
271100,Athletics,Athletics Men's Marathon
271101,Cycling,"Cycling Men's Team Pursuit, 4,000 metres"
271103,Athletics,Athletics Women's 4 x 400 metres Relay
271106,Hockey,Hockey Men's Hockey
271107,Football,Football Men's Football
271109,Rowing,Rowing Men's Lightweight Coxless Fours
271110,Basketball,Basketball Women's Basketball
271111,Luge,Luge Mixed (Men)'s Doubles
271112,Ski Jumping,"Ski Jumping Men's Large Hill, Individual"
271113,Ski Jumping,"Ski Jumping Men's Large Hill, Team"
271115,Bobsleigh,Bobsleigh Men's Four

In [51]:
list_of_events = events['Event'].values
count_of_participants_in_event = [df[df['Event'] == event]['Name'].count() for event in list_of_events]
events.insert(loc=len(events.columns), column='PCount', value=count_of_participants_in_event)
events

,Sport,Event,PCount
109352,Croquet,Croquet Mixed Doubles,2
117809,Athletics,Athletics Men's All-Around Championship,7
123223,Figure Skating,Figure Skating Men's Special Figures,3
147806,Swimming,Swimming Men's 100 metres Freestyle For Sailors,3
157315,Gymnastics,"Gymnastics Men's Individual All-Around, 4 Events",5
177943,Shooting,"Shooting Men's Muzzle-Loading Pistol, 25 metres",4
180286,Shooting,"Shooting Men's Free Pistol, 30 metres",5
185107,Racquets,Racquets Men's Singles,6
185108,Racquets,Racquets Men's Doubles,6
185185,Swimming,Swimming Men's 500 metres Freestyle,3
186006,Sailing,Sailing Mixed 10-20 Ton,6
197536,Swimming,Swimming Men's 220 yard Freestyle,4
200079,Sailing,Sailing Mixed 18 foot,2
202021,Athletics,"Athletics Men's 4,000 metres Steeplechase",8
209259,Swimming,Swimming Men's Plunge For Distance,5
212985,Cycling,Cycling Men's 1/3 mile,6
212988,Cycling,Cycling Men's 2 mile,5
213103,Cycling,"Cycling Men's 10,000 metres",6
214105,Aeronautics,Aeronautics Mixed Aeronautics,1
215492,Fencing,"Fencing Men's epee, Masters and Amateurs, Indi...",8
216862,Archery,Archery Men's Sur La Perche a La Herse,3
216863,Archery,Archery Men's Sur La Perche a La Pyramide,3
216980,Tennis,"Tennis Mixed Doubles, Covered Courts",16
222402,Shooting,"Shooting Men's Running Target, Single And Doub...",25
225266,Athletics,"Athletics Men's Javelin Throw, Both Hands",14
228387,Athletics,Athletics Men's Standing Triple Jump,14
228388,Sailing,Sailing Mixed 30 metres,3
230588,Roque,Roque Men's Singles,4
232614,Sailing,Sailing Mixed 2-3 Ton,22
233168,Athletics,Athletics Men's 56-pound Weight Throw,18
...,...,...,...
271070,Cross Country Skiing,Cross Country Skiing Men's Sprint,299
271071,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,1000
271072,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,892
271073,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,1100
271074,Cross Country Skiing,Cross Country Skiing Men's 10/10 kilometres Pu...,83
271077,Athletics,Athletics Women's Javelin Throw,500
271080,Athletics,Athletics Women's Shot Put,397
271083,Fencing,"Fencing Men's Foil, Individual",1357
271084,Fencing,"Fencing Men's Foil, Team",1305
271085,Fencing,"Fencing Men's epee, Team",1689
271086,Figure Skating,Figure Skating Mixed Ice Dancing,456
271087,Swimming,Swimming Men's 100 metres Butterfly,667
271088,Swimming,Swimming Men's 200 metres Butterfly,568
271090,Sailing,Sailing Men's Two Person Keelboat,98
271091,Volleyball,Volleyball Men's Volleyball,1861
271094,Speed Skating,"Speed Skating Men's 1,500 metres",885
271097,Speed Skating,"Speed Skating Men's 10,000 metres",510
271098,Speed Skating,"Speed Skating Men's 5,000 metres",730
271099,Wrestling,"Wrestling Women's Middleweight, Freestyle",68
271100,Athletics,Athletics Men's Marathon,2093
271101,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",1365
271103,Athletics,Athletics Women's 4 x 400 metres Relay,749
271106,Hockey,Hockey Men's Hockey,3958
271107,Football,Football Men's Football,5733
271109,Rowing,Rowing Men's Lightweight Coxless Fours,334
271110,Basketball,Basketball Women's Basketball,1256
271111,Luge,Luge Mixed (Men)'s Doubles,526
271112,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",810
271113,Ski Jumping,"Ski Jumping Men's Large Hill, Team",410
271115,Bobsleigh,Bobsleigh Men's Four,1715